---
- hosts: localhost
  connection: local
  gather_facts: False
  environment:
    ANSIBLE_HOST_KEY_CHECKING: False
  
  roles:
    - { role: create_ec2_vpc, mutiAZ: "yes", tags: [ "create" ] }
    - { role: clean-ec2-vpc, mutiAZ: "yes", tags: [ "clean" ] }


